#!/usr/bin/env python3
"""Pre-render generator for the website "Novidades / Releases" page.

Runs as a Quarto ``pre-render`` step (see website/_quarto.yml). Standard library
only — no third-party deps — so it works in the Quarto-only CI that publishes the
site. It produces three generated (git-ignored) artifacts:

* ``_variables.yml``        — exposes the current version to pages via {{< var version >}}
* ``assets/version.html``   — a <script> defining window.SAIRA_VERSION for the navbar badge
* ``_releases-pt.md`` /
  ``_releases-en.md``       — styled release cards, included by the two pages

The version comes from the repo-root DESCRIPTION; the highlights come from the
curated, bilingual website/data/releases.py.
"""

from __future__ import annotations

import html
import importlib.util
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
WEBSITE_DIR = SCRIPT_DIR.parent
REPO_ROOT = WEBSITE_DIR.parent

TAG_LABELS = {
    "pt": {"added": "Novo", "changed": "Mudou", "fixed": "Corrigido"},
    "en": {"added": "Added", "changed": "Changed", "fixed": "Fixed"},
}


def read_version() -> str:
    """Return the Version field from the repo-root DESCRIPTION."""
    for line in (REPO_ROOT / "DESCRIPTION").read_text(encoding="utf-8").splitlines():
        if line.lower().startswith("version:"):
            return line.split(":", 1)[1].strip()
    return "0.0.0"


def load_releases() -> list[dict]:
    """Import the curated highlights from website/data/releases.py."""
    spec = importlib.util.spec_from_file_location("releases", WEBSITE_DIR / "data" / "releases.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.RELEASES


def inline(text: str) -> str:
    """Escape HTML, then expand `code` and **bold** into safe inline markup."""
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", out)
    return out


def render_cards(releases: list[dict], lang: str) -> str:
    """Build the raw-HTML release cards for one language (blank-line separated)."""
    labels = TAG_LABELS[lang]
    blocks: list[str] = []
    for rel in releases:
        items = []
        for change_type, text in rel[lang]:
            tag = labels.get(change_type, change_type)
            items.append(
                f'    <li class="rel-item">'
                f'<span class="rel-tag rel-{change_type}">{tag}</span>'
                f'<span class="rel-text">{inline(text)}</span></li>'
            )
        card = (
            '<section class="release">\n'
            '  <header class="release-head">\n'
            f'    <span class="release-ver">v{rel["version"]}</span>\n'
            f'    <time class="release-date">{rel["date"]}</time>\n'
            '  </header>\n'
            '  <ul class="release-changes">\n'
            + "\n".join(items)
            + "\n  </ul>\n"
            "</section>"
        )
        blocks.append(card)
    return "<!-- generated by website/scripts/build_releases.py · do not edit -->\n\n" + "\n\n".join(blocks) + "\n"


def main() -> None:
    version = read_version()
    releases = load_releases()

    (WEBSITE_DIR / "_variables.yml").write_text(f'version: "{version}"\n', encoding="utf-8")
    (WEBSITE_DIR / "assets" / "version.html").write_text(
        f'<script>window.SAIRA_VERSION = "{version}";</script>\n', encoding="utf-8"
    )
    (WEBSITE_DIR / "_releases-pt.md").write_text(render_cards(releases, "pt"), encoding="utf-8")
    (WEBSITE_DIR / "_releases-en.md").write_text(render_cards(releases, "en"), encoding="utf-8")

    print(f"build_releases: version {version}, {len(releases)} releases -> PT/EN cards")


if __name__ == "__main__":
    main()
